version: '3'
services:
  front:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
    - ./:/usr/src/app
    command: sh -c "cd react-typescript-app && yarn start"
    ports:
    - "8000:3000"